[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"
channel = "1.86.0"
solana_version = "2.1.20"
[features]
resolution = true
skip-lint = false

[provider]
cluster = "localnet"
wallet = "~/.config/solana/localnet-keypair.json"

[registry]
url = "https://api.apr.dev"

[provider.mainnet]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "~/.config/solana/mainnet-keypair.json"

[provider.devnet]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/devnet-keypair.json"

[provider.testnet]
cluster = "https://api.testnet.solana.com"
wallet = "~/.config/solana/testnet-keypair.json"

[provider.localnet]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/localnet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests_ts/**/*.ts"

[programs.mainnet]
soccial_token = "4sbp1tZtsdUYnDjovQTyLvCCwxXZ78ifLNNLTAANV3Ci"

[programs.localnet]
soccial_token = "4sbp1tZtsdUYnDjovQTyLvCCwxXZ78ifLNNLTAANV3Ci"

[programs.devnet]
soccial_token = "4sbp1tZtsdUYnDjovQTyLvCCwxXZ78ifLNNLTAANV3Ci"

[programs.testnet]
soccial_token = "4sbp1tZtsdUYnDjovQTyLvCCwxXZ78ifLNNLTAANV3Ci"
